1000:
     id: A02
     resultado: "Version no soportada"
1001:
     id: A03
     resultado: " Dígito verificador del CUFE inválido"
1002:
     id: A03a
     resultado: "Documento duplicado"
1500:
     id: B02
     resultado: " Ambiente de destino de la FE inválido"
1501:
     id: B02a
     resultado: "Ambiente de destino del mensaje errado"
1502:
     id: B02b
     resultado: "CUFE malformado: Ambiente de destino"
1503:
     id: B03
     resultado: "Tipo de emisión inválida"
1504:
     id: B03a
     resultado: "CUFE malformado: Tipo de emisión"
1505:
     id: B03b
     resultado: "Este tipo de operación exige autorización previa"
1506:
     id: B04
     resultado: "Fecha y hora de inicio de la operación en contingencia no informada cuando tipo de emisión es contingencia"
1507:
     id: B04a
     resultado: "Fecha y hora de inicio de la operación en contingencia posterior a la fecha y hora de emisión de la FE"
1508:
     id: B04b
     resultado: "Tiempo excesivo en operación en contingencia"
1509:
     id: B05
     resultado: "Razón de la operación en contingencia no informada cuando el tipo de emisión es contingencia"
1510:
     id: B06
     resultado: "Tipo de documento inválido"
1511:
     id: B06a
     resultado: "CUFE malformado: Tipo de documento"
1512:
     id: B07
     resultado: "Número del documento fiscal inválido"
1513:
     id: B07a
     resultado: "Número del documento fiscal duplicado"
1514:
     id: B07b
     resultado: "CUFE malformado: Número del documento fiscal"
1515:
     id: B08
     resultado: "Punto de Facturación del documento fiscal inválida"
1516:
     id: B08a
     resultado: "CUFE malformado: Punto del documento fiscal"
1517:
     id: B09
     resultado: "Código de seguridad inválido"
1518:
     id: B09a
     resultado: "CUFE malformado: Código de seguridad"
1519:
     id: B10
     resultado: "Fecha de emisión muy antigua"
1520:
     id: B10a
     resultado: "Fecha de emisión muy alejada en el futuro"
1521:
     id: B10b
     resultado: "CUFE malformado: Fecha de emisión"
1535:
     id: B10c
     resultado: "Fecha de emisión en el futuro, posterior a 24 horas"
1522:
     id: B11
     resultado: "Fecha de salida muy antigua"
1523:
     id: B11a
     resultado: "Fecha de salida muy alejada en el futuro"
1524:
     id: B12
     resultado: "Naturaleza de la Operación inválida"
1525:
     id: B13
     resultado: "Tipo de Operación inválido"
1526:
     id: B14
     resultado: "Tipo de destino inválido"
1533:
     id: B14a
     resultado: "El destino de la operación no puede ser Panamá si el tipo de documento es Exportación"
1534:
     id: B14b
     resultado: "El destino de la operación no puede ser Extranjero si el Tipo de Documento es Factura de Operación Interna"
1527:
     id: B15
     resultado: "Formato de generación del CAFE inválido"
1528:
     id: B16
     resultado: "Manera de entrega del CAFE inválida"
1529:
     id: B17
     resultado: "Envío del contenedor para el receptor inválido"
1530:
     id: B18
     resultado: "Proceso de generación de la FE inválido"
1536:
     id: B18a
     resultado: "Informado generación de la FE vía web en webservice"
1531:
     id: B19
     resultado: "Tipo de transacción de venta inválido"
1532:
     id: B20
     resultado: "Operación entre contribuyentes realizada en sucursal de ventas al detal (retail) > a B/.200.00"
1560:
     id: B301
     resultado: "Regla de formación del RUC invalida"
1561:
     id: B301a
     resultado: "RUC inexistente en los registros de la DIRECCIÓN GENERAL DE INGRESOS"
1562:
     id: B301b
     resultado: "RUC no afiliado a la facturación electrónica"
1563:
     id: B301c
     resultado: "RUC impedido de facturar"
1564:
     id: B301d
     resultado: "CUFE malformado: RUC del emisor"
1565:
     id: B302
     resultado: "Literal inválido para ambiente de pruebas"
1566:
     id: B303
     resultado: "Código de sucursal inválido"
1567:
     id: B303a
     resultado: "CUFE malformado: Código de sucursal"
1568:
     id: B304
     resultado: "Latitud del punto de facturación inválida"
1569:
     id: B304a
     resultado: "Longitud del punto de facturación inválida"
1573:
     id: B3061
     resultado: "Código de Ubicación"
1570:
     id: B3062
     resultado: "Corregimiento donde se ubica la sucursal emisora no existe en el catálogo de corregimientos"
1571:
     id: B3063
     resultado: "Distrito donde se ubica el punto de facturación no existe en el catálogo de distritos"
1572:
     id: B3064
     resultado: "Provincia donde se ubica el punto de facturación no existe en el catálogo de provincias"
1600:
     id: B401
     resultado: "Tipo de receptor inválido"
1620:
     id: B401a
     resultado: "No fue informado tipo de receptor Extranjero con tipo de documento Exportación"
1601:
     id: B402
     resultado: "Regla de formación del RUC invalida"
1602:
     id: B402a
     resultado: "RUC inexistente en los registros de la DIRECCIÓN GENERAL DE INGRESOS"
1603:
     id: B402b
     resultado: "RUC del receptor contribuyente impedido de facturar"
1604:
     id: B402c
     resultado: "RUC del receptor no es de gobierno"
1621:
     id: B402d
     resultado: "Informado RUC de contribuyente tipo jurídico existente con tipo de receptor consumidor final"
1605:
     id: B403
     resultado: "Razón Social del receptor contribuyente no informada"
1606:
     id: B404
     resultado: "Dirección del receptor contribuyente no informada"
1617:
     id: B405
     resultado: "Ubicación del receptor no informada"
1618:
     id: B406
     resultado: "No informado el grupo de identificación del extranjero"
1619:
     id: B406a
     resultado: "informado el grupo de identificación del extranjero simultáneamente con grupo del RUC del contribuyente receptor"
1622:
     id: B4061
     resultado: "Informado RUC de contribuyente tipo jurídico existente con tipo de receptor Extranjero"
1616:
     id: B4051
     resultado: "Código de Ubicación del Receptor"
1607:
     id: B4052
     resultado: "Corregimiento donde se ubica el receptor contribuyente B401 = 01 y B4052 no existe en la no existe en el catálogo de corregimientos"
1608:
     id: B4053
     resultado: "Distrito donde se ubica el receptor contribuyente no existe en el catálogo de distritos"
1609:
     id: B4054
     resultado: "Provincia donde se ubica el receptor contribuyente no existe en el catálogo de provincias"
1610:
     id: B410
     resultado: "Código del país del receptor de la FE no existe en la tabla de países utilizada por la Autoridad Nacional de Aduanas"
1611:
     id: B410a
     resultado: "País del receptor de la FE debe ser Panamá si el destino de la operación es Panamá"
1612:
     id: B410b
     resultado: "País del receptor de la FE no puede ser Panamá si el destino de la operación es el extranjero (en caso de B14 = 2)"
1613:
     id: B410c
     resultado: "Informado código de país no existente en la Tabla 31"
1614:
     id: B411
     resultado: "No informado nombre del país receptor de la FE para código del país receptor de la FE no existente en la Tabla 31"
1615:
     id: B411a
     resultado: "Informado nombre del país del receptor de la FE no existente en la Tabla 31 simultáneamente con código existente en aquella tabla"
1650:
     id: B50
     resultado: "Grupo de Datos de Facturas en Caso de Exportación informado en operación interna"
1651:
     id: B50a
     resultado: "Grupo de Datos de Facturas en Caso de Exportación no informado en operación de exportación"
1652:
     id: B501
     resultado: "Condición de entrega no existe en la tabla de INCOTERMS"
1653:
     id: B502
     resultado: "Moneda de la operación de exportación no existe en la tabla de monedas"
1654:
     id: B503
     resultado: "No informada moneda de la operación de exportación para moneda de la operación de exportación no existente en la Tabla 33"
1655:
     id: B503a
     resultado: "Informada moneda de la operación de exportación para moneda de la operación de exportación no existente en la Tabla 33 simultáneamente con código existente en aquella tabla"
1656:
     id: B504
     resultado: "Informada moneda de la operación de exportación y no fue informado el tipo de cambio a la fecha de la operación"
1657:
     id: B505
     resultado: "Informada moneda de la operación de exportación y no fue informado el monto en la moneda extranjera"
1700:
     id: B601
     resultado: "Regla de formación del RUC invalida"
1719:
     id: B601a
     resultado: "Datos informados en grupos de campos de documento referenciado no concuerda con los datos del emisor"
1701:
     id: B603
     resultado: "Fecha de emisión del Documento Fiscal Referenciado muy antigua"
1702:
     id: B603a
     resultado: "Fecha de emisión del Documento Fiscal Referenciado posterior a la emisión de este documento"
1720:
     id: B603b
     resultado: "Fecha informada en el campo dFechaDFRef no concuerda con la fecha que se emitió la factura referenciada"
1703:
     id: B606
     resultado: "Estructura del CUFE de FE referenciada inválida"
1704:
     id: B606a
     resultado: "DV del CUFE de FE referenciada inválido"
1705:
     id: B606b
     resultado: "Nota de débito o de crédito que no referencia ninguna FE"
1706:
     id: B606c
     resultado: "Nota de débito o de crédito genérica referenciando una FE"
1707:
     id: B606d
     resultado: "No existe FE correspondiente a CUFE de FE referenciada"
1708:
     id: B606e
     resultado: "Factura de operación interna o de Zona Franca referenciando a una FE"
1709:
     id: B606f
     resultado: "CUFE referenciado con duplicado en la nota de crédito/débito"
1710:
     id: B606g
     resultado: "Los documentos electrónicos referenciados no concuerdan con el mismo receptor en la nota de crédito/débito"
1711:
     id: B606h
     resultado: "Monto total de nota de crédito/débito superior al monto total de la Factura referenciada"
1712:
     id: B606i
     resultado: "Nota de crédito que referencia una nota de crédito"
1713:
     id: B606j
     resultado: "Nota de débito que referencia una nota de débito"
1714:
     id: B606k
     resultado: "Fecha de emisión de la nota de crédito/debito supera los 180 día de la fecha de emisión de la FE"
1715:
     id: B606l
     resultado: "Nota de crédito que referencia una nota de débito"
1716:
     id: B606m
     resultado: "Nota de débito que referencia una nota de crédito"
1717:
     id: B606n
     resultado: "Monto de las notas de crédito o débito inconsistentes con el monto de la FE original referenciada"
1718:
     id: B606o
     resultado: "No se permite realizar notas de crédito/débito a una FE con un evento de anulación"
1750:
     id: B701
     resultado: "Regla de formación del RUC invalida"
2000:
     id: C01
     resultado: "Más de un Ítem en caso de venta de vehículo nuevo   "
2001:
     id: C02
     resultado: "Número secuencial del ítem duplicado   "
2002:
     id: C05
     resultado: "Unidad de medida del código interno no existe en el catálogo de unidades de medida"
2003:
     id: C07
     resultado: "Fecha de fabricación de medicamento no informado  "
2004:
     id: C08
     resultado: "Fecha de caducidad de medicamento no informado   "
2005:
     id: C09
     resultado: "Código de producto en el ítem no existe en la Codificación Panameña de Bienes y Servicios Abreviada  "
2006:
     id: C10
     resultado: "No informado código de producto en la Codificación Panameña de Bienes y Servicios en caso de venta a la  Administración Pública"
2007:
     id: C10a
     resultado: "No informado ningún código de producto en la Codificación Panameña de Bienes y Servicios"
2008:
     id: C10b
     resultado: "Código de producto en el ítem no existe en la Codificación Panameña de Bienes y Servicios Abreviada"
2010:
     id: C10c
     resultado: "Informado distintos códigos de productos de la Codificación Panameña de Bienes y Servicios en el ítem"
2009:
     id: C11
     resultado: "Unidad de medida no existe en el catálogo de unidades de  medida"
2050:
     id: C201
     resultado: "Precio unitario de la transferencia del bien o servicio muy elevado"
2051:
     id: C202
     resultado: "Valor del descuento superior al precio unitario"
2052:
     id: C202a
     resultado: "Informado valor del descuento en una operación no valorada"
2053:
     id: C203
     resultado: "Precio del ítem inválido"
2054:
     id: C204
     resultado: " Precio del acarreo, para este ítem porque ha sido informado que el acarreo es cobrado en el precio total específico, no puede ser informado "
2055:
     id: C205
     resultado: "Precio del seguro, para este ítem específico, no puede ser informado porque ha sido informado que el seguro es cobrado en el precio total"
2056:
     id: C206
     resultado: "Valor total del ítem inválido"
2150:
     id: C401
     resultado: "Fue informado el monto del ITBMS del ítem, y no fue informada tasa del ITBMS aplicable al ítem"
2151:
     id: C402
     resultado: "Fue informada tasa del ITBMS aplicable al ítem, y no fue informado el monto del ITBMS del ítem"
2152:
     id: C402a
     resultado: "Monto del ITBMS del ítem inválido"
2200:
     id: C501
     resultado: "Fue informado el monto ISC del ítem, y no fue informada tasa del ISC aplicable al ítem"
2201:
     id: C502
     resultado: "Fue informada tasa del ISC aplicable al ítem, y no fue informado el monto del ISC del ítem "
2202:
     id: C503
     resultado: "Monto del ISC del ítem inválido"
2300:
     id: C601
     resultado: "Código de otra tasa o impuesto por ítem se repite más de una vez"
2500:
     id: D02
     resultado: "Suma de los precios antes de impuesto invalida"
2501:
     id: D03
     resultado: "Total ITBMS invalido"
2502:
     id: D04
     resultado: "Total ISC invalido"
2516:
     id: D04a
     resultado: "El campo dTotISC es requerido porque informó el campo dValISC"
2517:
     id: D04b
     resultado: "El campo dValISC es requerido porque informo el campo dTotISC"
2503:
     id: D05
     resultado: "Suma total de monto gravado invalida"
2504:
     id: D06
     resultado: "Suma de los descuentos y bonificaciones concedidos sobre el valor total de la factura invalida"
2505:
     id: D07
     resultado: "No se puede informar valor del acarreo cobrado en el precio total porque ha sido informado valor del acarreo en alguno de los ítems"
2506:
     id: D08
     resultado: "No se puede informar valor del seguro cobrado en el precio total porque ha sido informado valor de seguro en alguno de los ítems"
2507:
     id: D09
     resultado: "Valor total de la factura inválido"
2508:
     id: D09a
     resultado: "Suma de los valores de las fracciones de pago a plazo inválida"
2509:
     id: D09b
     resultado: "Valor total de la factura muy elevado"
2515:
     id: D09c
     resultado: "Valor total de la Factura elevada en venta al consumidor final"
2510:
     id: D10
     resultado: "Suma de los valores recibidos inválida"
2511:
     id: D11
     resultado: "Vuelto entregado al cliente inválido"
2512:
     id: D12
     resultado: "Tiempo de pago inválido"
2513:
     id: D13
     resultado: "Número total de ítems de la factura inválido"
2514:
     id: D14
     resultado: "Valor total de los ítems inválidos"
2600:
     id: D301
     resultado: "Forma de pago de la factura inválida"
2601:
     id: D302
     resultado: "Falta la descripción de forma de pago no listada en el formato"
2602:
     id: D302a
     resultado: "Informada descripción de forma de pago no listada en el formato simultáneamente con forma de pago existente"
2650:
     id: D401
     resultado: "Código de Retención a aplicar no existe en el catálogo de objetos de retención"
2651:
     id: D402
     resultado: "Monto de la retención inválida"
2800:
     id: D601
     resultado: "El total de códigos de otras tasas o impuestos a nivel de todos los ítems, no concuerda con el total de códigos de otras tasas o impuestos a nivel del grupo de totales"
2801:
     id: D601a
     resultado: "El código de otras tasas o impuestos a nivel de ítems, difiere del código de otras tasas o impuestos a nivel del grupo de totales"
2802:
     id: D602
     resultado: "El monto de otras tasas o impuestos por código a nivel de ítems, difiere del monto de otras tasas o impuestos por código a nivel del grupo de totales "
2803:
     id: D602
     resultado: "Código de otra tasa o impuesto se repite más de una VEZ"
3050:
     id: E050
     resultado: "Modalidad de la operación de venta de vehículos nuevos inválida"
3051:
     id: E051
     resultado: "Falta la descripción de modalidad de la operación de venta de vehículos nuevos"
3052:
     id: E051a
     resultado: "Informada descripción de modalidad de la operación de venta de vehículos nuevos no existente simultáneamente con código válido de modalidad de la operación de venta de vehículos nuevos"
3060:
     id: E060
     resultado: "Tipo de combustible inválido"
3061:
     id: E061
     resultado: "Falta la descripción de modalidad de tipo de combustible"
3062:
     id: E061a
     resultado: "Informada descripción de modalidad de tipo de combustible no existente simultáneamente con código válido de descripción de modalidad de tipo de combustible"
3068:
     id: E068
     resultado: "Tipo de pintura inválido"
3069:
     id: E069
     resultado: "Falta la descripción de modalidad de tipo de pintura"
3070:
     id: E069a
     resultado: "Informada descripción de modalidad de tipo de pintura no existente simultáneamente con código válido de descripción de pintura de tipo de combustible"
3071:
     id: E070
     resultado: "Tipo del vehículo inexistente en tabla de tipos de vehículo del Departamento de Registro Vehicular"
3072:
     id: E071
     resultado: "Especie del vehículo inexistente en tabla de especies de vehículo del Departamento de Registro Vehicular"
3073:
     id: E072
     resultado: "Condición del vehículo inválida"
3600:
     id: F203
     resultado: "Unidad del peso total inválida"
3650:
     id: F25
     resultado: "Regla de formación del RUC invalida"
3651:
     id: F254
     resultado: "Corregimiento donde se ubica local de la entrega no existe en el catálogo de corregimientos"
3652:
     id: F255
     resultado: "Distrito donde se ubica local de la entrega no existe en el catálogo de distritos"
3653:
     id: F2544
     resultado: "Provincia donde se ubica local de la entrega no existe en el catálogo de provincias"
4000:
     id: G101
     resultado: "Dirección de la página web de consulta de la DIRECCIÓN GENERAL DE INGRESOS en el código QR errada"
4001:
     id: G102
     resultado: "Ambiente de destino de la FE en el código QR no corresponde al informado en el área de datos de la FE"
4002:
     id: G103
     resultado: "CUFE en el código QR no corresponde al informado en el área de datos de la FE "
4003:
     id: G104
     resultado: "Fingerprint en el código QR mal formado"
