"01":
     nombre: "Factura de Operación Interna"
"02":     
     nombre: "Factura de Importación"
"03":     
     nombre: "Factura de Exportación"
"04":     
     nombre: "Nota de Crédito Referente a una o Varias FE"
"05":     
     nombre: "Nota de Débito Referente a una o Varias FE"
"06":     
     nombre: "Nota de Crédito Genérica"
"07":     
     nombre: "Nota de Débito Genérica"
"08":     
     nombre: "Factura de Zona Franca"
"09":     
     nombre: "Reembolso"
