"01":
     nombre: "Autorización de Uso Previa, operación normal"
"02":     
     nombre: "Autorización de Uso Previa, operación en contingencia"
"03":     
     nombre: "Autorización de Uso Posterior, operación normal"     
"04":     
     nombre: "Autorización de Uso posterior, operación en contingencia"     
